pull_request_rules:
  - name: Test passed for code changed
    conditions:
      - or:
          - base=main
      - "status-success=Unittest AMD64 Ubuntu 18.04"
      - "status-success=lint"
    actions:
      label:
        add:
          - ci-passed

  - name: Remove ci-passed when some test failed
    conditions:
      - or:
          - base=main
      - or:
          - "check-failure=Unittest AMD64 Ubuntu 18.04"
          - "check-failure=lint"
    actions:
      label:
        remove:
          - ci-passed
