build:
	@echo "Building CDC ..."
	@go build -o ../bin/cdc main/main.go

build-position:
	@echo "Building Position ..."
	@go build -o ../bin/cdc-position main/main.go

build-meta-position:
	@echo "Building Meta Position ..."
	@go build -o ../bin/cdc-meta-position main/main.go