address: 0.0.0.0:8444
maxTaskNum: 100
metaStoreConfig:
  storeType: etcd
  etcdEndpoints:
    - localhost:2379
#  mysqlSourceUrl: root:root@tcp(127.0.0.1:3306)/milvus-cdc?charset=utf8
  mysqlSourceUrl: milvuscdc:1qaz@WSX@tcp(dev-vdc-mysql.cluster-c0ybmd1el2xt.us-west-2.rds.amazonaws.com:3306)/milvuscdc?charset=utf8
  rootPath: cdc
sourceConfig:
  etcdAddress:
    - localhost:2379
  etcdRootPath: by-dev
  etcdMetaSubPath: meta
  readChanLen: 10
  defaultPartitionName: _default
  pulsar:
    address: pulsar://localhost:6650
    webAddress: localhost:80
    maxMessageSize: 5242880
    tenant: public
    namespace: default
#  kafka:
#    address: 127.0.0.1:9092
enableReverse: false
reverseMilvus:
  host: localhost
  port: 19530
  username: root
  password: 123456
  enable_tls: false
  ignore_partition: true
  connect_timeout: 10
currentMilvus:
  host: 127.0.0.1
  port: 19530
maxNameLength: 256
